### ISSUE TITLE
Application.properties file cannot read System variables on ec2

### ISSUE THREAD

**Issue by watchdogoblivion** [1908-aug19-java/Project2-Samuel-Chris-Kyle-BackEnd#9]
The application.properties file was set up to use dollar notation ${system.variable}, to get the system environment variables that specify the database driver, url, username, and password. When setting the environment variables on windows, the application.properties file cannot read the specified variables in the dollar brackets. Eclipse grants the option to specify the environment variables via run configurations. When set that way, the application.properties file can read them. This posses a problem since we are not using an IDE when deploying our jar on the EC2. So we have no way to use that intermediary layer to set our environment variables. When running the jar on the EC2 the problem was persisted, and the logs show that the application.properties cannot read the variables correctly.

**Comment by watchdogoblivion** [comment]
The bug should be resolved with the next pull request, but we still need to test it in the EC2. I removed the dollar notation from the applicaton.properties file since it can only currently be used to grab the IDE's environment variables and not the system's environment variables. in order to get the system variables I added a custom configuration class. The class is a spring component configuration which tells spring that is should be considered for generating bean definitions. From there the bean is defined and is marked as primary to take precedence over any other potential candidates since spring performs various component and file scans. The environment variables are then extracted programatically with the System class. It was tested and worked on my windows environment so it should work in the EC2 if the matching environment variables are set in the .bashrc file.

**Comment by chrstphrclmn** [comment]
Samuel's Merge (#11) resolved this issue.

**Comment by watchdogoblivion** [comment]
Tested solution on EC2. It failed. Reopening issue.

**Comment by watchdogoblivion** [comment]
When testing on EC2, the application still failed to read environment variables. Tried multiple restarts. Created a setenv.sh script and exported variables. That did not fix the problem. Went through both the server.xml and context.xml files in the conf folder, and added global references.That did not fix the problem. Settled on reading from an external application.properties file. That solution is yet to be tested since the changes must be merged. I simply added a propertysource annotation on the main class and the path to the file that i transferred to the EC2. The properties file now holds the visible credentials instead of using a sigil to attempt to reference an environment variable. Will test after the merge has been completed. 
Please see below  docs for more information
https://tomcat.apache.org/tomcat-7.0-doc/RUNNING.txt
https://tomcat.apache.org/tomcat-8.0-doc/jndi-datasource-examples-howto.html

**Comment by watchdogoblivion** [comment]
Tested using separate properties file and it failed. Changed the postgres dialect. Then Allowed incomming connections on EC2 for port 8081. Problem is now resolved.
